<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ip-172-31-45-13.us-east-2.compute.internal" name="com.seedbank.common.tests.RegistrationTests" tests="7" failures="4" timestamp="1 Mar 2019 12:06:59 GMT" time="5.009" errors="2">
  <testcase name="checkForInvalidMobileNumber_Alphabetic" time="0.000" classname="com.seedbank.common.tests.RegistrationTests"/>
  <testcase name="checkForInvalidOTP_Alphabetic" time="0.000" classname="com.seedbank.common.tests.RegistrationTests"/>
  <testcase name="checkForInvalidOTP_SpecialChar" time="0.000" classname="com.seedbank.common.tests.RegistrationTests"/>
  <testcase name="checkForInvalidOTP_AlphaNumeric" time="0.000" classname="com.seedbank.common.tests.RegistrationTests">
    <error type="java.lang.AssertionError" message="TEst Method failed">
      <![CDATA[java.lang.AssertionError: TEst Method failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.seedbank.common.tests.RegistrationTests.checkForInvalidOTP_AlphaNumeric(RegistrationTests.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.seedbank.common.gui.Run.execute(Run.java:98)
	at com.seedbank.common.gui.Run.formXML(Run.java:75)
	at com.seedbank.common.gui.Run.main(Run.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:283)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- checkForInvalidOTP_AlphaNumeric -->
  <testcase name="checkForInvalidMobileNumber_SpecialChar" time="5.008" classname="com.seedbank.common.tests.RegistrationTests">
    <error type="java.lang.AssertionError" message="TEst Method failed">
      <![CDATA[java.lang.AssertionError: TEst Method failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.seedbank.common.tests.RegistrationTests.checkForInvalidMobileNumber_SpecialChar(RegistrationTests.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.seedbank.common.gui.Run.execute(Run.java:98)
	at com.seedbank.common.gui.Run.formXML(Run.java:75)
	at com.seedbank.common.gui.Run.main(Run.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:283)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- checkForInvalidMobileNumber_SpecialChar -->
  <testcase name="checkForInvalidMobileNumber_checkMobileNumberLength" time="0.000" classname="com.seedbank.common.tests.RegistrationTests"/>
  <testcase name="checkForInvalidMobileNumber_AlphaNumeric" time="0.001" classname="com.seedbank.common.tests.RegistrationTests"/>
</testsuite> <!-- com.seedbank.common.tests.RegistrationTests -->
